### PR TITLE
Code formatting setup, code actions and guidleines

### PR DESCRIPTION
**Pull request by aishenreemo**

### CODE REVIEW

**Comment by aishenreemo** [comment]
#5

**Review by directormac — CHANGES_REQUESTED** [review]
Let the pnpm yaml stay as we will use it on building for deployments at cloud providers.

**Comment by aishenreemo** [comment]
Huwag po muna i-merge, hindi pa tapos, thank you.

**Comment by aishenreemo** [comment]
> Let the pnpm yaml stay as we will use it on building for deployments at cloud providers.

Okay gotyu.

**Comment by directormac** [comment]
@DDuran19  Review for VanillaJS
@itsmenoahpoli  Review for Vue
@kurtobando  Review for React

**Review by Gengineering — APPROVED** [review]

**Review by kurtobando — APPROVED** [review]
All good to me. Good ahead

**Comment by aishenreemo** [comment]
### Overview

This pull request aims to enhance the code formatting consistency across the project using Prettier. The changes in this pull request include:

- Adding Prettier configuration file for consistent code formatting.
- Introducing GitHub Code Actions to automatically format code using Prettier.
- Updating the README with code formatting guidelines.

### Code Formatting Guidelines

To maintain a consistent code style, we are introducing the following code formatting guidelines:

1. **Indentation**: Use **four spaces** for indentation. Avoid using tabs.
2. **Semicolons**: Putting semi-colons at the end of a statement is required.
3. **Single vs. Double Quotes**: Use double quotes (`"`) for strings unless escaping is required.
4. **Line Length**: Limit lines to a maximum of 100 characters. If necessary, break long lines into multiple lines for readability.

### GitHub Code Actions with Prettier

We have integrated GitHub Code Actions with Prettier to check code formatting whenever a pull request is opened or updated. This will check if your changes adhere to the defined formatting guidelines.

### Running Prettier

Before creating the pull request, follow these steps:

1. Install Dependencies: Ensure that you have Node.js and `pnpm` installed on your machine.
2. Change Directory: `cd` into your desired directory (for example `cd packages/react-todo`)
3. Install `pnpm` Dependencies: Run `pnpm install` to install the required dependencies.
4. Run Prettier: Execute `pnpm run write` to run Prettier and format code.

**Comment by aishenreemo** [comment]
Hi, naging super complicated ng thread na ito haha, gumawa ako panibagong pull request #9 para mas concise, ill close this pr na without merging it. thank you

**Pull request closed without merging**
